version: '3'

services:

  archivy:
    image: archivy-godhart:latest
    
    build:
      context: ../
      dockerfile: docker/Dockerfile
    # cap_add:  # that one were reuiqred for draw.io once
    #   - SYS_ADMIN
    container_name: archivy
#   networks: # If you are using a reverse proxy, you will need to edit this file to add Archivy to your reverse proxy network. You can also remove the host-to-container port mapping, as that should be handled by the reverse proxy
    ports:
      - 5000:5000 # this is a host-to-container port mapping. If your Docker environment already uses the host's port `:5000`, then you can remap this to any `<port>:5000` you need
    volumes:
      - ./.data:/archivy/data # this mounts the ./archivy_data/ folder from the host's working directory into the container
      - ./.config:/archivy/.local/share/archivy # this mounts the docker-managed archivy_config volume from the host's working directory into the container
    environment:
      ARCHIVY_VIEW_ONLY         : False
      ARCHIVY_SHOW_PLUGINS      : False
      ARCHIVY_SHOW_BOOKMARKLET  : False
      ARCHIVY_SHOW_SETTINGS     : False
      ARCHIVY_SHOW_USEREDIT     : False
      RENDER_DEFAULT_RAWSVG     : True
  elasticsearch:
    image: elasticsearch:7.9.0
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw # this mounts the docker-managed elasticsearch_data volume into the container and makes it writable
    environment:
      - "discovery.type=single-node"

volumes:
  elasticsearch_data:

# Update index with:
# docker exec -it archivy archivy index
